import { v4 as uuidv4 } from 'uuid';

const data = [
    {
        id: uuidv4(),
        title: "html",
        body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab laborum sequi, dolore itaque placeat vitae, quis cum aliquam ipsa iusto nam, molestiae delectus officiis deleniti magni consectetur ad sunt quidem ipsum illo distinctio qui. Non laborum quisquam quas fugiat? Tempore cum nihil repellendus voluptas nobis, mollitia sint cupiditate! Nisi asperiores fugiat, optio architecto suscipit, perspiciatis reiciendis illo velit commodi minus id. Tenetur totam labore reprehenderit soluta voluptatum accusantium dignissimos doloremque ratione sapiente laboriosam. Temporibus ea similique veritatis delectus culpa quod veniam quos nesciunt reprehenderit, nobis impedit nemo asperiores dolor hic saepe natus illo, consequuntur error? Facere, at numquam. Culpa distinctio, ullam nesciunt facere, aut asperiores nobis sapiente quae harum ducimus, at eaque assumenda! Nisi soluta consequatur aperiam. Id eligendi nisi quaerat officia nemo saepe, temporibus similique quas veniam, obcaecati excepturi maiores impedit? Recusandae cupiditate atque saepe eveniet maiores libero aliquid provident nisi voluptate, qui totam reprehenderit quidem! Provident, quae mollitia tempore deleniti blanditiis totam? Iure harum modi autem. Doloremque minima ex aliquid culpa laudantium cupiditate laborum accusantium corporis dolor. Est iure cum ducimus recusandae ipsum explicabo. Nemo dolor, quae, aliquid quibusdam cupiditate consequatur ipsum fuga ducimus nostrum incidunt hic adipisci fugiat? Sapiente, quod perspiciatis. Quia facere earum at quasi non!"

    },
    {
        id: uuidv4(),
        title: "css",
        body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab laborum sequi, dolore itaque placeat vitae, quis cum aliquam ipsa iusto nam, molestiae delectus officiis deleniti magni consectetur ad sunt quidem ipsum illo distinctio qui. Non laborum quisquam quas fugiat? Tempore cum nihil repellendus voluptas nobis, mollitia sint cupiditate! Nisi asperiores fugiat, optio architecto suscipit, perspiciatis reiciendis illo velit commodi minus id. Tenetur totam labore reprehenderit soluta voluptatum accusantium dignissimos doloremque ratione sapiente laboriosam. Temporibus ea similique veritatis delectus culpa quod veniam quos nesciunt reprehenderit, nobis impedit nemo asperiores dolor hic saepe natus illo, consequuntur error? Facere, at numquam. Culpa distinctio, ullam nesciunt facere, aut asperiores nobis sapiente quae harum ducimus, at eaque assumenda! Nisi soluta consequatur aperiam. Id eligendi nisi quaerat officia nemo saepe, temporibus similique quas veniam, obcaecati excepturi maiores impedit? Recusandae cupiditate atque saepe eveniet maiores libero aliquid provident nisi voluptate, qui totam reprehenderit quidem! Provident, quae mollitia tempore deleniti blanditiis totam? Iure harum modi autem. Doloremque minima ex aliquid culpa laudantium cupiditate laborum accusantium corporis dolor. Est iure cum ducimus recusandae ipsum explicabo. Nemo dolor, quae, aliquid quibusdam cupiditate consequatur ipsum fuga ducimus nostrum incidunt hic adipisci fugiat? Sapiente, quod perspiciatis. Quia facere earum at quasi non!"

    },
    {
        id: uuidv4(),
        title: "javaScript",
        body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab laborum sequi, dolore itaque placeat vitae, quis cum aliquam ipsa iusto nam, molestiae delectus officiis deleniti magni consectetur ad sunt quidem ipsum illo distinctio qui. Non laborum quisquam quas fugiat? Tempore cum nihil repellendus voluptas nobis, mollitia sint cupiditate! Nisi asperiores fugiat, optio architecto suscipit, perspiciatis reiciendis illo velit commodi minus id. Tenetur totam labore reprehenderit soluta voluptatum accusantium dignissimos doloremque ratione sapiente laboriosam. Temporibus ea similique veritatis delectus culpa quod veniam quos nesciunt reprehenderit, nobis impedit nemo asperiores dolor hic saepe natus illo, consequuntur error? Facere, at numquam. Culpa distinctio, ullam nesciunt facere, aut asperiores nobis sapiente quae harum ducimus, at eaque assumenda! Nisi soluta consequatur aperiam. Id eligendi nisi quaerat officia nemo saepe, temporibus similique quas veniam, obcaecati excepturi maiores impedit? Recusandae cupiditate atque saepe eveniet maiores libero aliquid provident nisi voluptate, qui totam reprehenderit quidem! Provident, quae mollitia tempore deleniti blanditiis totam? Iure harum modi autem. Doloremque minima ex aliquid culpa laudantium cupiditate laborum accusantium corporis dolor. Est iure cum ducimus recusandae ipsum explicabo. Nemo dolor, quae, aliquid quibusdam cupiditate consequatur ipsum fuga ducimus nostrum incidunt hic adipisci fugiat? Sapiente, quod perspiciatis. Quia facere earum at quasi non!"

    },
    {
        id: uuidv4(),
        title: "React",
        body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab laborum sequi, dolore itaque placeat vitae, quis cum aliquam ipsa iusto nam, molestiae delectus officiis deleniti magni consectetur ad sunt quidem ipsum illo distinctio qui. Non laborum quisquam quas fugiat? Tempore cum nihil repellendus voluptas nobis, mollitia sint cupiditate! Nisi asperiores fugiat, optio architecto suscipit, perspiciatis reiciendis illo velit commodi minus id. Tenetur totam labore reprehenderit soluta voluptatum accusantium dignissimos doloremque ratione sapiente laboriosam. Temporibus ea similique veritatis delectus culpa quod veniam quos nesciunt reprehenderit, nobis impedit nemo asperiores dolor hic saepe natus illo, consequuntur error? Facere, at numquam. Culpa distinctio, ullam nesciunt facere, aut asperiores nobis sapiente quae harum ducimus, at eaque assumenda! Nisi soluta consequatur aperiam. Id eligendi nisi quaerat officia nemo saepe, temporibus similique quas veniam, obcaecati excepturi maiores impedit? Recusandae cupiditate atque saepe eveniet maiores libero aliquid provident nisi voluptate, qui totam reprehenderit quidem! Provident, quae mollitia tempore deleniti blanditiis totam? Iure harum modi autem. Doloremque minima ex aliquid culpa laudantium cupiditate laborum accusantium corporis dolor. Est iure cum ducimus recusandae ipsum explicabo. Nemo dolor, quae, aliquid quibusdam cupiditate consequatur ipsum fuga ducimus nostrum incidunt hic adipisci fugiat? Sapiente, quod perspiciatis. Quia facere earum at quasi non!"

    },
    {
        id: uuidv4(),
        title: "Nodejs",
        body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab laborum sequi, dolore itaque placeat vitae, quis cum aliquam ipsa iusto nam, molestiae delectus officiis deleniti magni consectetur ad sunt quidem ipsum illo distinctio qui. Non laborum quisquam quas fugiat? Tempore cum nihil repellendus voluptas nobis, mollitia sint cupiditate! Nisi asperiores fugiat, optio architecto suscipit, perspiciatis reiciendis illo velit commodi minus id. Tenetur totam labore reprehenderit soluta voluptatum accusantium dignissimos doloremque ratione sapiente laboriosam. Temporibus ea similique veritatis delectus culpa quod veniam quos nesciunt reprehenderit, nobis impedit nemo asperiores dolor hic saepe natus illo, consequuntur error? Facere, at numquam. Culpa distinctio, ullam nesciunt facere, aut asperiores nobis sapiente quae harum ducimus, at eaque assumenda! Nisi soluta consequatur aperiam. Id eligendi nisi quaerat officia nemo saepe, temporibus similique quas veniam, obcaecati excepturi maiores impedit? Recusandae cupiditate atque saepe eveniet maiores libero aliquid provident nisi voluptate, qui totam reprehenderit quidem! Provident, quae mollitia tempore deleniti blanditiis totam? Iure harum modi autem. Doloremque minima ex aliquid culpa laudantium cupiditate laborum accusantium corporis dolor. Est iure cum ducimus recusandae ipsum explicabo. Nemo dolor, quae, aliquid quibusdam cupiditate consequatur ipsum fuga ducimus nostrum incidunt hic adipisci fugiat? Sapiente, quod perspiciatis. Quia facere earum at quasi non!"

    },
]

export default data;